resolver: nightly-2022-10-11
packages:
- .
ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages -Wmissing-deriving-strategies
    -Wno-unticked-promoted-constructors -Wprepositive-qualified-module
extra-deps:
- package-version-0.3@sha256:190490fde31f673054d317c7eb8c0638591c5b41b96860cb2ce232ea75665dcd,2792
- git: https://github.com/tbidne/algebra-simple.git
  commit: c8aaa4495964ecea9bb898c4fcb8b1c718ecc813
- git: https://github.com/tbidne/bounds.git
  commit: 7a8832ef4a55d565e72fab553a4d485329235bf7
- git: https://github.com/tbidne/byte-types.git
  commit: a7e1cd9824ca72c970a8a33ecd77256863bfc071
nix:
  shell-file: nix/stack.nix