name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "9.2.7"
          - "9.4.5"
        os:
        - "macos-latest"
        - "ubuntu-latest"
        - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Configure
        run: cabal configure --enable-tests --enable-benchmarks

      - name: Compile
        run: cabal build

      - name: Functional Tests
        run: cabal test functional

      # Only benchmark on ubuntu to reduce maintenance burden as other
      # benchmarks are not really actionable.

      - name: Benchmark Tasty
        if: ${{ matrix.os == 'ubuntu-latest' }}
        id: bench-tasty
        run: |
          cabal bench bench-tasty --benchmark-options '
            --csv bench/tasty/bench_${{ matrix.os }}_${{ matrix.ghc }}_ci.csv
            --svg bench/tasty/bench_${{ matrix.os }}_${{ matrix.ghc }}_ci.svg
            --baseline bench/tasty/baseline_${{ matrix.os }}_${{ matrix.ghc }}_ci.csv
            --fail-if-slower 20
            --fail-if-faster 20'

      - name: Benchmark Criterion
        if: ${{ failure() && steps.bench-tasty.conclusion == 'failure' && matrix.os == 'ubuntu-latest' }}
        run: |
          cabal bench bench-criterion --benchmark-options '
            --csv bench/criterion/bench_${{ matrix.os }}_${{ matrix.ghc }}_ci.csv
            --output bench/criterion/bench_${{ matrix.os }}_${{ matrix.ghc }}_ci.html'

      - uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.bench-tasty.conclusion == 'failure' }}
        with:
          name: build-artifacts
          path: |
            bench/criterion/bench_${{ matrix.os }}_${{ matrix.ghc }}_ci.csv
            bench/criterion/bench_${{ matrix.os }}_${{ matrix.ghc }}_ci.html
            bench/tasty/bench_${{ matrix.os }}_${{ matrix.ghc }}_ci.csv
            bench/tasty/bench_${{ matrix.os }}_${{ matrix.ghc }}_ci.svg
  nix:
    strategy:
      fail-fast: false
      matrix:
        os:
        - "macos-latest"
        - "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/897876e4c484f1e8f92009fd11b7d988a121a4e7.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Compile & Test
        run: nix build
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Setup nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/897876e4c484f1e8f92009fd11b7d988a121a4e7.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Formatting
        run: |
          nix run .#format
          git diff --exit-code --color=always

      - name: HLint
        run: nix run .#lint